/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.Monster;
import NapakalakiGame.BadConsequence;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author carlos
 */
public class MonsterView extends javax.swing.JPanel {

    private Monster monsterModel;
    
    
    public MonsterView() {
        initComponents();
    }
    
    public void setMonster(Monster t){
        // se actualiza el atributo de referencia
        monsterModel=t;

        String nombre_icon = "/GUI/monsters/" + t.getName() + ".jpg";
        System.out.println(nombre_icon);
        
        Icon icono = new ImageIcon(MonsterView.class.getResource(nombre_icon));
        jImagen.setIcon(icono);
        // la siguiente instrucción hace que los cambios en la vista sean efectivos
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jImagen = new javax.swing.JLabel();

        jImagen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jImagen;
    // End of variables declaration//GEN-END:variables
}
