/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.CombatResult;
import NapakalakiGame.Napakalaki;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author carlos
 */
public class NapakalakiView extends javax.swing.JFrame {

    private Napakalaki napakalakiModel;
    
    public NapakalakiView() {
        initComponents();
    }

    public void setNapakalaki(Napakalaki model){
        // se actualiza el atributo de referencia
        napakalakiModel=model;
        
        // Establecemos el panel del jugador
        VistaPlayer.setNapakalaki(model, this);
        
        // se actualiza la vista del tesoro
        this.VistaPlayer.setPlayer(napakalakiModel.getCurrentPlayer());
        this.VistaMonster.setMonster(napakalakiModel.getCurrentMonster());
        
        // Establecemos que valores o botones son visibles o se permiten usar
        this.VistaMonster.setVisible(false);
        this.LabelCombatResult.setVisible(false);
        this.LabelPasarTurno.setVisible(false);
        this.ButtonCombat.setEnabled(false);
        this.ButtonNextTurn.setEnabled(false);
        this.ButtonMeetTheMonster.setEnabled(true);
        
        
        // Se fuerza la actualización visual del panel
        VistaMonster.repaint();
        VistaMonster.revalidate();
        VistaPlayer.repaint();
        VistaPlayer.revalidate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonMeetTheMonster = new javax.swing.JButton();
        ButtonCombat = new javax.swing.JButton();
        ButtonNextTurn = new javax.swing.JButton();
        VistaMonster = new GUI.MonsterView();
        LabelCombatResult = new javax.swing.JLabel();
        LabelPasarTurno = new javax.swing.JLabel();
        VistaPlayer = new GUI.PlayerView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButtonMeetTheMonster.setText("Meet the Monster");
        ButtonMeetTheMonster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMeetTheMonsterActionPerformed(evt);
            }
        });

        ButtonCombat.setText("Combat");
        ButtonCombat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCombatActionPerformed(evt);
            }
        });

        ButtonNextTurn.setText("Next turn");
        ButtonNextTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNextTurnActionPerformed(evt);
            }
        });

        LabelCombatResult.setText("Resultado:");

        LabelPasarTurno.setText("Pasar turno");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(VistaPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 532, Short.MAX_VALUE)
                .addComponent(VistaMonster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelPasarTurno)
                    .addComponent(LabelCombatResult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonMeetTheMonster, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonCombat, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonNextTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VistaPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VistaMonster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelCombatResult)
                        .addGap(18, 18, 18)
                        .addComponent(LabelPasarTurno))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonMeetTheMonster, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ButtonCombat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ButtonNextTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonMeetTheMonsterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMeetTheMonsterActionPerformed
        this.VistaMonster.setVisible(true);
        this.ButtonCombat.setEnabled(true);
        this.ButtonMeetTheMonster.setEnabled(false);
    }//GEN-LAST:event_ButtonMeetTheMonsterActionPerformed

    private void ButtonCombatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCombatActionPerformed
        this.ButtonCombat.setEnabled(false);
        
        CombatResult result = napakalakiModel.developCombat();

        setNapakalaki(napakalakiModel);

        if (result == CombatResult.WINGAME) {   // Gana combate y partida

            JOptionPane.showMessageDialog(null, "El jugador " + this.napakalakiModel.getCurrentPlayer().getName() + 
                    " ha llegado al nivel 10. GANA EL JUEGO.");
            System.exit(0);
        }else{
            if(result == CombatResult.WIN){ // Gana combate
                LabelCombatResult.setText("HAS GANADO EL COMBATE.");
                LabelCombatResult.setVisible(true);
            }else{  // Pierde el combate
                LabelCombatResult.setText("HAS PERDIDO EL COMBATE.");
                LabelCombatResult.setVisible(true);
                LabelCombatResult.setForeground(Color.blue);
            }
                
        }
        
        this.ButtonNextTurn.setEnabled(true);
        this.ButtonMeetTheMonster.setEnabled(false);
    }//GEN-LAST:event_ButtonCombatActionPerformed

    private void ButtonNextTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNextTurnActionPerformed
        // Se hacen en el set
        //this.ButtonNextTurn.setEnabled(false);
        //this.VistaMonster.setVisible(false);
        boolean turno=this.napakalakiModel.nextTurn();

        if(turno){
            this.setNapakalaki(napakalakiModel);
            this.ButtonMeetTheMonster.setEnabled(true);
            this.ButtonNextTurn.setEnabled(false);
            LabelPasarTurno.setVisible(false);
        }else{
            LabelPasarTurno.setText("No puedes pasar turno porque no cumples las condiciones.");
            LabelPasarTurno.setVisible(true);
            LabelPasarTurno.setForeground(Color.red);
        }
        
        
    }//GEN-LAST:event_ButtonNextTurnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCombat;
    private javax.swing.JButton ButtonMeetTheMonster;
    private javax.swing.JButton ButtonNextTurn;
    private javax.swing.JLabel LabelCombatResult;
    private javax.swing.JLabel LabelPasarTurno;
    private GUI.MonsterView VistaMonster;
    private GUI.PlayerView VistaPlayer;
    // End of variables declaration//GEN-END:variables
}
