/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.Treasure;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author carlos
 */
public class TreasureView extends javax.swing.JPanel {

    private Treasure treasureModel;
    private boolean selected=false;
    
    
    public TreasureView() {
        initComponents();
    }
    
    public void setTreasure (Treasure aTreasure) {
        // se actualiza el atributo de referencia
        treasureModel = aTreasure;
        // se actualiza la vista del tesoro
        String nombre_icon = "/GUI/treasures/" + aTreasure.getName() + ".jpg";
        System.out.println(nombre_icon);
        
        Icon icono = new ImageIcon(MonsterView.class.getResource(nombre_icon));
        jImagen.setIcon(icono);
        
        // la siguiente instrucción hace que los cambios en la vista sean efectivos
        repaint();
    }
    
    public boolean isSelected(){
        return selected;
    }
    
    public Treasure getTreasure(){
        return treasureModel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jImagen = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jImagen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 30, 255), 1, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // Seleccionamos o deseleccionamos
        if(selected==true){
            selected=false;
            // Cambiamos color para identificar el seleccionado
            jImagen.setBorder(BorderFactory.createLineBorder(Color.blue));
        }else{
            if(selected==false)
            selected=true;
            // Cambiamos color para identificar el seleccionado
            jImagen.setBorder(BorderFactory.createLineBorder(Color.red));
        }
        
        repaint();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jImagen;
    // End of variables declaration//GEN-END:variables
}
